#!/bin/sh
echo "Welcome to Caravel 0.2\n----------------------\nAvailable commands:\n"
echo "build	runs the build script and launches a live reload 
	server at port 3000"
echo "seed	cleans existing records and seeds the database"
echo "behat	runs tests"
echo "dumpdb	dumps the database to a file at /vagrant/dbdumps"
echo "\n"
